#!/bin/bash

######################################################
#
# init.d script for CalCentral
#
# chkconfig: 2345 90 05
# description: start script for calcentral
# processname: calcentral
#
######################################################

HOST=$(uname -n)
if [[ "${HOST}" = *calcentral* ]]; then
  APP_MODE="calcentral"
else
  APP_MODE="junction"
fi
RUN_AS_USER="app_${APP_MODE}"
BASE="${HOME}/calcentral"
START_SCRIPT="${BASE}/script/start-torquebox.sh"
STOP_SCRIPT="${BASE}/script/stop-torquebox.sh"
DOC_ROOT="/var/www/html/${APP_MODE}"
OFFLINE_FILE="${DOC_ROOT}/calcentral-in-maintenance"
MAINT_HTML="${DOC_ROOT}/index_maintenance.html"
EMERGENCY_HTML="${DOC_ROOT}/index_emergency.html"
INDEX_HTML="${DOC_ROOT}/index.html"

if [ -x "/usr/bin/id" ]; then
  CURR_USER="$(/usr/bin/id -u -n)"
else
  CURR_USER="${USER}"
fi

if [ "${CURR_USER}" != "${RUN_AS_USER}" ]; then
  echo "Only ${RUN_AS_USER} can execute this script"
  exit 1
fi

online() {
  if [ -f "${OFFLINE_FILE}" ]; then
    rm "${OFFLINE_FILE}"
  fi
}

offline () {
  touch "${OFFLINE_FILE}"
}

maint () {
  cp -p "${MAINT_HTML}" "${INDEX_HTML}"
  offline
}

emergency () {
  cp -p "${EMERGENCY_HTML}" "${INDEX_HTML}"
  offline
}

start() {
  if [ ! -x "${START_SCRIPT}" ]; then
    echo "${START_SCRIPT} does not exist or is not executable"
    exit 1
  fi
  echo "Starting ${APP_MODE}..."
  ${START_SCRIPT} || exit 1
}

stop() {
  if [ ! -x "${STOP_SCRIPT}" ]; then
    echo "${STOP_SCRIPT} does not exist or is not executable"
    exit 1
  fi
  echo "Shutting down ${APP_MODE}..."
  ${STOP_SCRIPT}
}

status() {
  # The return value of this function may be used by other scripts
  JPS_RESULTS=$(jps -mlv | grep torquebox | cut -d ' ' -f 1)

  if [ -n "${JPS_RESULTS}" ]; then
    echo "PID: ${JPS_RESULTS}"
  else
    echo "PID: no pid found"
  fi
}

case "${1}" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 10
    start
    ;;
  status)
    status
    ;;
  online)
    online
    ;;
  offline)
    offline
    ;;
  maint)
    maint
    ;;
  emergency)
    emergency
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart|status|online|offline|maint|emergency}"
esac

exit 0
