export const FETCH_CHECKLIST_ITEMS_START = 'FETCH_CHECKLIST_ITEMS_START';
export const FETCH_CHECKLIST_ITEMS_SUCCESS = 'FETCH_CHECKLIST_ITEMS_SUCCESS';
export const FETCH_CHECKLIST_ITEMS_FAILURE = 'FETCH_CHECKLIST_ITEMS_FAILURE';

export const FETCH_WEB_MESSAGES_START = 'FETCH_WEB_MESSAGES_START';
export const FETCH_WEB_MESSAGES_SUCCESS = 'FETCH_WEB_MESSAGES_SUCCESS';
export const FETCH_WEB_MESSAGES_FAILURE = 'FETCH_WEB_MESSAGES_FAILURE';

export const FETCH_AGREEMENTS_START = 'FETCH_AGREEMENTS_START';
export const FETCH_AGREEMENTS_SUCCESS = 'FETCH_AGREEMENTS_SUCCESS';
export const FETCH_AGREEMENTS_FAILURE = 'FETCH_AGREEMENTS_FAILURE';
