const linkLookup = {
  activateFPP: 'UC_FA_FINRES_ACTIVATE_FPP',
  bearsFinancialSuccess: 'UC_FA_FINRES_BEARS_FIN_SUCCESS',
  berkeleyInternationalOffice: 'UC_FA_FINRES_INTERNATIONAL',
  billingFAQ: 'UC_FA_FINRES_BILLING_FAQ',
  calStudentCentral: 'UC_FA_FINRES_CAL_STUDNT_CENTRL',
  debitAccount: 'UC_FA_FINRES_CAL1CARD',
  costOfAttendance: 'UC_FA_FINRES_COA',
  delegateAccess: 'UC_FA_FINRES_DELEGATE',
  directDeposit: 'UC_FA_FINRES_DIRECT_DEP',
  directDepositEnroll: 'UC_FA_FINRES_DIRECT_DEP_ENRL',
  directDepositManage: 'UC_FA_FINRES_DIRECT_DEP_MANAGE',
  dreamActApplication: 'UC_FA_FINRES_DREAM_ACT',
  emergencyLoan: 'UC_FA_FINRES_EMERG_LOAN',
  emergencyLoanApply: 'UC_FA_FINRES_EMERG_LOAN_APPLY',
  finaidForms: 'UC_FA_FINRES_FA_FORMS',
  finaidSummary: 'UC_FA_FINRES_FA_SUMMARY',
  finaidSummaryDelegate: 'UC_FA_FINRES_FA_SUMMARY_DELEGA',
  fafsa: 'UC_FA_FINRES_FAFSA',
  fafsaVerify: 'UC_FA_FINRES_FAFSA_VERIFY',
  finaidOffice: 'UC_FA_FINRES_FASO',
  federalStudentLoans: 'UC_FA_FINRES_FED_LOANS',
  gradFinancialSupport: 'UC_FA_FINRES_GRAD_FIN_SUPPORT',
  iGrad: 'UC_FA_FINRES_IGRAD',
  leavingCal: 'UC_FA_FINRES_LEAVING_CAL',
  loanRepaymentCalculator: 'UC_FA_FINRES_LOAN_CALCULATOR',
  mealPlanBalance: 'UC_FA_FINRES_MEAL_PLAN',
  mealPlanLearn: 'UC_FA_FINRES_MEAL_PLAN_LEARN',
  nslds: 'UC_FA_FINRES_NSLDS',
  paymentOptions: 'UC_FA_FINRES_PAYMENT_OPTIONS',
  stateInstitutionalLoans: 'UC_FA_FINRES_STATE_INST_LOANS',
  studentAdvocateOffice: 'UC_FA_FINRES_ADVOCATE',
  summerEstimator: 'UC_FA_FINRES_SUMMER_ESTIMATOR',
  summerFees: 'UC_FA_FINRES_SUMMER_FEES',
  summerSchedule: 'UC_FA_FINRES_SUMMER_SCHEDULE',
  summerWebsite: 'UC_FA_FINRES_SUMMER_WEB',
  summerCancelWithdraw: 'UC_FA_FINRES_SUMMER_WITHDRAW',
  tenNinetyEightT: 'UC_FA_FINRES_1098T',
  tenNinetyEightTView: 'UC_FA_FINRES_1098T_VIEW',
  tuitionAndFees: 'UC_FA_FINRES_TUITION_AND_FEES',
  tuitionAndFPP: 'UC_FA_FINRES_TUIT_AND_FPP',
  withdrawCancel: 'UC_FA_FINRES_WITHDRAW',
  workStudy: 'UC_FA_FINRES_WORK_STUDY',
};

const getLink = (key, links) => {
  return links[linkLookup[key]];
};

export default getLink;
