application:
  # Set to true if testing production env without Apache/Nginx
  serve_static_assets: false
  # Set to "https://" if running behind Apache/Nginx + https
  protocol: 'http://'
  fake_cas: false
  fake_cas_id: '1' # Change this to the UID you want to fake cas auth with.
  # WebMock is not thread-safe, and so fake proxy support should
  # be disabled when no fakes are needed (e.g., in production).
  fake_proxies_enabled: true
  # timeout (in seconds) for outgoing http request establishment
  outgoing_http_timeout: 30
  layer: development
  # Lifespan of session cookie
  session_expiration: <%= 4.hours %>
  # Restrict deployment to the SIS service 'calcentral' or the ETS service 'bcourses'.
  # The default is to support all CalCentral/Junction services.
  provided_services: ['calcentral', 'bcourses']

slate_auth_handler:
  client: 'Slate'
  handler: 'ClientAuthenticationHandler'
  handler_casv5: 'slateAuthenticationHandler'

logger:
  level: <%= ENV['LOGGER_LEVEL'] || WARN %>
  stdout: <%= ENV['LOGGER_STDOUT'] %>
  slow_query_threshold_in_ms: 700
  slow_request_threshold_in_ms:
    default: 30000
    /api/my/status: 10000
  proxy_threshold_in_ms: 8000

cas_server: 'https://auth.berkeley.edu/cas'

cas_logout_url: 'https://auth.berkeley.edu/cas/logout'

cas_use_name_identifier: false

# Database settings
oracle:
  adapter: oracle_enhanced
  database: <%= ENV['DB_ENV_ORACLE_DB'] || 'bcsdev' %>
  username: <%= ENV['DB_ENV_ORACLE_USER'] || 'calcentral' %>
  password: <%= ENV['DB_ENV_ORACLE_PASS'] || 'secret' %>
  host: <%= ENV['DB_ENV_ORACLE_HOSTT'] || 'localhost' %>
  port: <%= ENV['DB_ENV_ORACLE_PORT'] || '1521' %>
  pool: 95
  timeout: 5000

edodb:
  adapter: nulldb

campusdb:
  adapter: nulldb

terms:
  # Limit how far back our academic history goes.
  oldest: spring-2010
  # This term and earlier will pull academic data from legacy CampusOracle. Later terms will pull from EdoOracle.
  legacy_cutoff: summer-2016
  # Timestamp in UTC, needed when testing against test Campus data.
  # Can also be used to force selection of a "current term" different
  # from the default.
  fake_now:
  # If hub term API is disabled (see hub_term_api in features flags),
  # use /public/json/terms.json or this file
  use_term_definitions_json_file: false
  term_definitions_json_file:

test_sqlite:
  pool: 3

# Proxy support
# MUST BE SET FOR DEVELOPMENT & PRODUCTION
# Example generated with SecureRandom.base64(32)
oauth2:
  key: 'IeGpe9iq27Glqujd8pGH1+xM8C/ofm97Lp74N+6cN0I='
  encryption: 'aes-256-cbc'

# Proxy settings
# Set "fake: true" for any inaccessible ones
canvas_proxy:
  admin_access_token: 'someMumboJumbo'
  # URL for Canvas server
  url_root: 'http://localhost:12345'
  fake: false
  account_id: '90242'
  default_grading_scheme_id: '4068930'
  export_directory: 'tmp/canvas'
  lti_key: 'someMumboJumbo'
  lti_secret: 'someMumboJumbo'
  # Only used for testing + recording responses
  test_user_id: '300846'
  test_user_access_token: 'someMumboJumbo'
  mixed_sis_user_id: true
  # Set to any string to make integration scripts create CSV files and log intended updates
  # without actually changing anything in Canvas.
  dry_run_import: <%= ENV['CANVAS_DRY_RUN_IMPORT'] || '' %>
  # Throttle automatic site membership refresh if more than these many enrollments are being dropped.
  max_deleted_enrollments: 1000
  # URL for scripts to point to CalCentral/Junction
  app_provider_host: 'http://localhost:3000'
  test_admin_id:
  test_servers:
  test_cas_url: 'https://auth-test.berkeley.edu/cas'
  # If reports are provided through Google Drive, this is the UID that creates them.
  reporter_uid:
  # Course sites before this term will not be linked to campus SIS data.
  oldest_official_term: 2016-D

ldap:
  host: 'ldap.berkeley.edu'
  port: 636
  application_bind: 'uid=someApp,ou=applications,dc=berkeley,dc=edu'
  application_password: 'someMumboJumbo'

google_proxy:
  client_id: 1
  client_secret: 'bogusClientSecret'
  scope:
    - profile
    - email
    - https://www.googleapis.com/auth/calendar
    - https://www.googleapis.com/auth/tasks
    - https://www.googleapis.com/auth/drive.readonly.metadata
    - https://mail.google.com/mail/feed/atom/
  fake: false
  #Maps to tammi.chang.clc@gmail.com. Used for testing + recording responses
  test_user_access_token: 'bogusAccessToken'
  test_user_refresh_token: 'bogusRefreshToken'
  atom_mail_feed_url: 'https://mail.google.com/mail/feed/atom/'

cal_link_proxy:
  fake: false
  base_url: 'https://callink.berkeley.edu'
  public_key: secret set in production
  private_key: secret set in production

clearing_house_proxy:
  fake: false
  base_url: 'https://secure.studentclearinghouse.org/sssportalui/authenticate'
  app_id: ''
  app_key: ''

eft_proxy:
  fake: true
  # QA Environment
  base_url: 'https://eftstudent-qa.berkeley.edu/api/'
  token: 'secret'

mailgun_proxy:
  fake: false
  base_url: 'https://api.mailgun.net/v3'
  domain: 'bcourses-mail.berkeley.edu'
  api_key: 'secret'

financials_proxy:
  fake: false
  base_url: 'https://apis.berkeley.edu/uat/sis/v2/cfv/students'
  app_id: ''
  app_key: ''

hub_term_proxy:
  fake: false
  app_id: ''
  app_key: ''
  base_url: 'https://apis.berkeley.edu/uat/sis/v1/terms'

textbooks_proxy:
  fake: false
  base_url: 'https://api.studentstore.com/webcomm-rest'

webcast_proxy:
  fake: false
  feed_file_path: ''

blog_latest_release_notes_feed_proxy:
  fake: false
  base_url: 'https://www.ets.berkeley.edu/news-archive/calcentral-release-notes/feed'

cal1card_proxy:
  fake: false
  base_url: 'https://webstage.housing.berkeley.edu/c1c/dyn'
  username: 'secret'
  password: 'secret'

# Analytics settings ID
# This will need to be different for every server (dev/qa/production)
google_analytics_id: UA-XXXXXX-X

# Sentry URL
# We use https://getsentry.com for our JavaScript Error logging
sentry_url: 'https://facf7ad7bd7047f0a356e9322107ce50@app.getsentry.com/7185'

# Cache settings. 0 means never expire.
# WARNING: memcached's upper limit is 30 days. Specifying longer expiration than that will
# result in entries expiring instantly.
cache:
  # Array of server addresses in cluster (for memcached). These must match the hostnames
  # of the application cluster for CalCentral's BackgroundJobsCheck to work correctly.
  servers: ['localhost']
  maximum_expires_in: <%= 29.days %>
  race_condition_ttl: <%= 10.seconds %>
  pool: 20
  stale_connection_flush_interval: <%= 30.seconds %>
  store: 'memcached'
  log_level: <%= Logger::WARN %>
  expiration:
    default: <%= 35.minutes %>
    failure: <%= 30.seconds %>
    BackgroundJobsCheck: <%= 29.days %>
    MyAcademics::Merged: <%= 15.minutes %>
    MyAcademics::MyAcademicStatus: <%= 15.minutes %>
    MyActivities::Merged: <%= 10.minutes %>
    MyBadges::Merged: <%= 2.hours %>
    MyCampusLinksController: NEXT_08_00
    MyClasses::Merged: <%= 10.minutes %>
    MyTasks::Merged: <%= 10.minutes %>
    UpNext::MyUpNext: NEXT_00_00
    User::Api: NEXT_08_00
    User::AuthenticationValidator: <%= 8.hours %>
    User::AuthenticationValidator::short: <%= 5.minutes %>
    Cal1card::Photo: <%= 4.hours %>

    Canvas::CourseStudents: <%= 15.minutes %>
    CanvasBackgroundJobs: <%= 24.hours %>

    Advising::MyAdvising: <%= 2.hours %>

    Berkeley::Terms: NEXT_08_00
    Berkeley::LegacyTerms: <%= 29.days %>
    Finaid::TimeRange: <%= 4.hours %>

    CampusOracle::CourseSections: NEXT_08_00
    CampusOracle::UserAttributes: NEXT_08_00
    CampusOracle::UserCourses::All: NEXT_08_00

    EdoOracle::CourseSections: <%= 8.hours %>
    EdoOracle::UserCourses::All: <%= 15.minutes %>
    EdoOracle::UserCourses::Base: <%= 8.hours %>

    Canvas::MergedUserSites: <%= 30.minutes %>
    Canvas::UserCourses: <%= 30.minutes %>
    Canvas::Groups: <%= 30.minutes %>
    Canvas::UserActivityStream: <%= 10.minutes %>
    Canvas::Terms: <%= 8.hours %>
    Canvas::Todo: <%= 20.minutes %>
    Canvas::UpcomingEvents: <%= 20.minutes %>

    MyBadges::GoogleDrive: <%= 10.minutes %>

    MyTasks::GoogleTasks: <%= 4.minutes %>

    CalLink::Memberships: <%= 4.hours %>
    CalLink::Organization: <%= 4.hours %>

    Textbooks::Proxy: <%= 24.hours %>

    Api::ServiceAlerts: <%= 24.hours %>

    CampusSolutions::AddressLabel: <%= 29.days %>
    CampusSolutions::AddressType: <%= 29.days %>
    CampusSolutions::ConfidentialStudentMessage: <%= 24.hours %>
    CampusSolutions::Country: <%= 29.days %>
    CampusSolutions::CurrencyCode: <%= 29.days %>
    CampusSolutions::DelegateManagementURL: <%= 24.hours %>
    CampusSolutions::DelegateStudents: <%= 24.hours %>
    CampusSolutions::DelegateTermsAndConditions: <%= 24.hours %>
    CampusSolutions::EthnicitySetup: <%= 29.days %>
    CampusSolutions::LanguageCode: <%= 29.days %>
    CampusSolutions::Link: <%= 24.hours %>
    CampusSolutions::MessageCatalog: <%= 24.hours %>
    CampusSolutions::MyChecklist: <%= 15.minutes %>
    CampusSolutions::MyDeposit: <%= 2.minutes %>
    CampusSolutions::MyHigherOneUrl: <%= 1.seconds %>
    CampusSolutions::NameType: <%= 29.days %>
    CampusSolutions::ResidencyMessage: <%= 24.hours %>
    CampusSolutions::SirConfig: <%= 24.hours %>
    CampusSolutions::State: <%= 29.days %>
    CampusSolutions::SlrDeeplink: <%= 24.hours %>
    CampusSolutions::Translate: <%= 24.hours %>
    CampusSolutions::DashboardUrl: <%= 29.days %>

    CalnetCrosswalk::ByUid: <%= 4.hours %>
    CalnetCrosswalk::ByCsId: <%= 4.hours %>
    User::Identifiers::Cached: <%= 4.hours %>

    # Merge of independently cached feeds.
    HubEdos::MyStudent: <%= 5.minutes %>

# Cache warmer settings
cache_warmer:
  # Number to decrement db pool to limit the number of warmer threads
  fudge_factor: 1

ce_diploma:
  supported_terms: []

# Bearfacts JMS event queue
ist_jms:
  fake: true
  enabled: true
  freshen_recording: false
  connections:
    - url: 'tcp://localhost:61616'
      queues: ['testqueue']
      #  username: USERNAME
      #  password: PASSWORD

# This will enable http basic auth for the app and should NEVER be enabled in production
developer_auth:
  enabled: false
  password: topsecret!

background_threads:
  min: 2,
  max: 2,
  max_queue: 0 # unbounded work queue

background_jobs_check:
  time_between_pings: <%= 5.minutes %>

youtube_splash_id: '3Iz1NT9QKjI'

ui_selenium:
  base_url: https://calcentral-dev.berkeley.edu
  cal_net_url: https://auth-test.berkeley.edu
  canvas_base_url: https://ucberkeley.beta.instructure.com
  canvas_qa_sub_account: secret
  google_auth_url: /api/google/request_authorization?force_domain=false
  layer: development

  # Alternative browsers for Selenium tests: chrome, safari, ie
  web_driver: firefox

  google_task_timeout: 12
  page_event_timeout: 10
  page_load_timeout: 20
  academics_timeout: 20
  canvas_update_timeout: 60
  canvas_username: secret
  canvas_password: secret
  canvas_id: secret
  test_user_password: secret
  ets_qa_ldap_username: secret
  ets_qa_ldap_password: secret
  ets_qa_gmail_username: secret
  ets_qa_gmail_password: secret
  admin_uid: secret

campus_solutions_proxy:
  fake: true
  base_url: 'https://bcs-web-dev-03.is.berkeley.edu:8443/PSIGW/RESTListeningConnector/PSFT_CS'
  logout_url: 'https://bcs-web-dev-03.is.berkeley.edu:8443/psp/logout/EMPLOYEE/HRMS/?cmd=logout'
  username: secret
  password: secret
  http_timeout_seconds: 30

hub_edos_proxy:
  fake: true
  base_url: 'https://sis-integration.berkeley.edu/apis/sis'
  username: secret
  password: secret
  http_timeout_seconds: 30

hub_person_proxy:
  fake: true
  base_url: 'https://sis-integration.berkeley.edu/apis/sis'
  username: secret
  password: secret
  http_timeout_seconds: 30

hub_enrollments_proxy:
  fake: true
  base_url: 'https://sis-integration.berkeley.edu/dev/apis/sis/v2/enrollments/students'
  username: secret
  password: secret
  http_timeout_seconds: 30

hub_classes_proxy:
  base_url: 'https://sis-integration.berkeley.edu/dev/apis/sis/'
  username: secret
  password: secret
  http_timeout_seconds: 30

calnet_crosswalk_proxy:
  fake: true
  enabled: true
  base_url: 'https://registry-d1.calnet.1918.berkeley.edu:8453/registry-service/api/v1/identifiers'
  username: secret
  password: secret
  http_timeout_seconds: 30

# A feature will be disabled if the corresponding feature-flag is false or nil.
features:
  advising: false
  advising_academic_planner: false
  advising_student_success: false
  allow_legacy_fallback: true
  allow_alt_email_addr_for_enrollments: true
  authentication_validator: false
  background_jobs_check: true
  cal1card: false
  campus_links_from_file: false
  class_info_enrollment_section_overview: false
  class_info_enrollment_tab: false
  course_manage_official_sections: false
  cs_academic_planner: false
  cs_advising_links: false
  cs_advisor_student_lookup: false
  cs_billing: false
  cs_committees: false
  cs_degree_progress_grad_advising: false
  cs_degree_progress_grad_student: false
  cs_degree_progress_ugrd_advising: false
  cs_degree_progress_ugrd_student: false
  cs_degree_progress_ugrd_ucnr_apr_link: false
  cs_degree_progress_ugrd_ucch_apr_link: false
  cs_delegated_access: false
  cs_enrollment_card: false
  cs_fin_aid: false
  cs_fin_aid_award_compare: false
  cs_logout: false
  cs_profile: true
  cs_profile_emergency_contacts: false
  cs_profile_languages: false
  cs_profile_work_experience: false
  cs_sir: true
  employment_appointments: true
  enrollment_verification: false
  final_exam_schedule_student: false
  final_exam_schedule_instructor: false
  gpa_calculator: true
  hub_term_api: true
  ldap_student_affiliations: false
  legacy_caldap: true
  my_fin_aid: false
  prevent_acting_as_users_from_posting: true
  reauthentication: true
  regstatus: true
  reserved_capacity: false
  reserved_capacity_link: false
  standings: true
  textbooks: false
  textbooks_new_store: false
  transcript_request_link_cred_solutions: false
  videos: false
  view_completed_calgrant_link: true
  alumni_homepage: true
